---
# vars file for defilan-osconfig
go_version: "1.23.6"

# Shared package lists using YAML anchors to avoid duplication
_shared_homebrew_taps: &shared_taps
  - hashicorp/tap
  - aws/tap
  - twilio/brew

_shared_homebrew_packages: &shared_homebrew
  - neovim
  - tmux
  - git-extras
  - thefuck
  - go
  - kubectl
  - skaffold
  - awscli
  - hashicorp/tap/terraform
  - hashicorp/tap/packer
  - aws-sam-cli
  - node
  - redis
  - molecule
  - battery
  - twilio
  - exercism
  - yarn
  - podman
  - minikube
  - kubectx
  - helm

_shared_apt_packages: &shared_apt
  - neovim
  - tmux
  - git-extras
  - thefuck
  - zsh
  - golang-go

config_packages:
  lightweight:
    homebrew_cask_packages:
      - arc
      - iterm2
      - 1password
      - rectangle
      - istat-menus
  developer:
    homebrew_taps: *shared_taps
    homebrew_packages: *shared_homebrew
    homebrew_cask_packages:
      - arc
      - iterm2
      - visual-studio-code
      - 1password
      - rectangle
      - font-hack-nerd-font
      - jetbrains-toolbox
      - switchresx
      - istat-menus
      - bruno
      - obs
      - cursor
    apt_packages: *shared_apt
  home:
    homebrew_taps: *shared_taps
    homebrew_packages: *shared_homebrew
    homebrew_cask_packages:
      - arc
      - iterm2
      - visual-studio-code
      - 1password
      - rectangle
      - font-hack-nerd-font
      - jetbrains-toolbox
      - nordvpn
      - switchresx
      - discord
      - istat-menus
      - signal
      - bruno
      - gimp
      - obs
      - krisp
      - cursor
    apt_packages: *shared_apt

defilan_directories:
  - ~/stuffy
  - ~/stuffy/code
  - ~/stuffy/playground
