galaxy_info:
  author: Christopher Maher
  description: Base Config for Defilan Macs and Debian systems
  company: Defilan Technologies

  license: MIT

  min_ansible_version: "2.14"

  platforms:
    - name: MacOSX
      versions:
        - all
    - name: Debian
      versions:
        - all
    - name: Ubuntu
      versions:
        - all

  galaxy_tags: []

dependencies: []
